### ISSUE TITLE
Test http mode

### ISSUE THREAD

**Issue by jpmens** [owntracks/quicksetup#16]
We've done almost all testing on quicksetup with MQTT, which is obvious as we prefer that protocol.

I've tested HTTP POST, but we need to test whether an OwnTracks device (Android, iOS) correctly works on HTTP.

Reminder: we do not support WS over MQTT.

**Comment by ckrey** [comment]
Tested with Android and iOS app. Just change mode to HTTP and add url=https://server.domain/owntracks/pub

**Comment by jpmens** [comment]
Marvelous, thanks.

**Comment by jpmens** [comment]
That can't be. From the nginx access.log:

```
- jane [10/Feb/2024:08:41:04 +0000] "GET /owntracks/pub HTTP/1.1" 404
```

**Comment by jpmens** [comment]
Ah, we expect POST obvioiusly.
