### ISSUE TITLE
Permission issue -- testing Quicksetup

### ISSUE THREAD

**Issue by whmoorejr** [owntracks/quicksetup#22]
I'm running MQTT and owntracks on the same raspberry pi.  I have everything working pretty well except for a couple oddities with having a few older phones in my setup (running older versions of owntracks).  It still works, but can't do certain things like enable them to receive commands to force a location update. (Seperate issue but not a show stopper)

On the server side, I want to be able to have more control over manipulating data.  The data store is located in the default location which works, but I started seeing issues when I tried to delete a user.  During testing I created a user with a typo in the name.  Re-created a user on that device, but the old user is still there.

I tried the "Kill" command but got the "No comprendo" message.  Doing a version check, however, shows that "WITH_KILL = yes" so ?
deleting a file is combersome as I can't use cyberduck or GUI due to permissions.  I have to telnet in and use sudo commands to delete stuff in the var/spool/owntracks/recorder/store/rec/(user_directory)/(YYYY-MM.rec).  

When I finally deleted the user file and folder under rec directory, the user is still visible on devices and on the recorder page.

I also tried getting around the permissions thing by moving the store to home/me/Documents/owntracks...../store (I made a full copy at that location).... then I get an error with owntracks...  something about ghash Permissions Denied.

So I know I messed up something somewhere but I'm not sure what direction to go in now.

**Comment by whmoorejr** [comment]
On the front end, I have the fields accross the top.  Next to the person icon, the page defaults to "Show all" with a down arrow.  When I click it, it doesn't show any of the users I've added so far.  The download button on the right of the page opens up a window with an empty json {}.  With the far right information icon, I get owntracks/frontend (2.12.0), but owntracks/recorder (Loading version...) <-- doesn't ever populate.

Following the quicksetup, I did verify that the Recorder is saving publised data
`$ tail /var/spool/owntracks/recorder/store/rec/bill/myphone/2024-02.rec`

Side note, from some of your other posts, it looks like you are a mac guy.... have you ever used the home automation platform, "Indigo" ?

**Comment by jpmens** [comment]
Would you please refresh the Frontend page? It will need to re-acquire data from the Recorder API in order to populate users, etc.

> Following the quicksetup, I did verify that the Recorder is saving publised data

Good.

You should also be able to access data via the API (URL above)

> have you ever used the home automation platform, "Indigo" ?

I have not. I gave up all home automation experiments, of which I did a few, several years ago. I am a huge believer in physical switches for lamps, etc. -- they always work. :-)

**Comment by jpmens** [comment]
Do the other pages work for you?
- Device table
- Live map

**Comment by whmoorejr** [comment]
**Frontend** still isn't working for me.  Device table and Live map are working fine.
using this: `https://192.168.1.86/owntracks/map/index.html?user=bill&device=myphone&format=geojson&from=2024-02-19` I did get the pretty map which showed me driving all over Houston today.

API is working for me as long as I get the formatting right.  :-) 
working: https://192.168.1.86/owntracks/api/0/last?fields=tst,tid,addr,topic,isotst
No Comprendo: https://192.168.1.86/owntracks/api/0/last[-d user=bill [-d device=myphone]]
working: https://192.168.1.86/owntracks/api/0/last?user=bill&device=myphone  (same as above, just formatted different)

But, yes... I can access all my data in one way or another.  The frontend might be my go-to location to check device locations/history... but I can't figure out why it doesn't see the data.

I see where the frontend setup stuff is "quicksetup/files/frontend" Other than that, I'm not sure what to look for.  Sorry I'm not much help.

Suggestion for Quicksetup.... maybe in the debugging section at the bottom.... add a few check things, like the lines to check that stuff is running properly:
$ sudo systemctl satus mosquitto / ot-recorder / etc.

**Comment by jpmens** [comment]
The penny might be dropping ... I notice in the examples above, that  you are using an IP address to access your site and API, so I am going to assume you are doing that to access Frontend as well?

That doesn't work.

The reason you configured `dns_domain` in `configuration.yaml` was so that Quicksetup would enroll an SSL certificate for you. Assuming that domain is `bill.example`, the only correct method of accessing your site is `https://bill.example/...`. You've had to use `-k` on curl(1), and you've had to add exceptions to your Web browsers for accessing `https://192.168.1.68`. 

My question: but why? Why not use the URL with the domain name in it?

**Comment by jpmens** [comment]
In Safari you got a big fat warning:

![rabbit-10735](https://github.com/owntracks/quicksetup/assets/60706/e38e2564-99d5-46c9-ad0a-b6008a174f40)

**Comment by jpmens** [comment]
Should you for whichever reason (which would interest me) not be able to do so, you ought to be able to work around the issue with the following small trick.

Edit the `/etc/hosts` file on your Mac

```console
$ sudo nano /etc/hosts
```

and add a line which looks like the following (`bill.example` being the domain name you configured in `dns_domain`):

```
192.168.1.86  bill.example
```
Back in the shell, a 

```console
$ ping -c2 bill.example
```

should show the 192.168.1.86 address.

Then please try to access `https://bill.example/owntracks`

**Comment by jpmens** [comment]
699102

**Comment by whmoorejr** [comment]
> The penny might be dropping ... I notice in the examples above, that you are using an IP address to access your site and API, so I am going to assume you are doing that to access Frontend as well?
> 
> That doesn't work.

Weird habit, maybe?  I would use the DNS address for an off-site connection, the URL for a LAN connection and localhost or 127.0.0.1 if I'm accessing from the same machine.

However, when I changed my url to use the DNS instead of the IP address, everything worked as expected.

That new frontend... absolutely beautiful.  I love it!  Simple, yet detailed and lightning fast.  It would probably take 10 minutes or more to get that kind of information out an alternative platform, like Life360.
