### ISSUE TITLE
User-specific waypoints for inline/otrc configuration

### ISSUE THREAD

**Issue by jpmens** [owntracks/quicksetup#27]
Similarly to how we create friend-specific MQTT ACLs, we could add user-specific waypoints to the inline/otrc configuration during bootstrapping.

A directory `waypoints/` would contain `<username>.json` with an array of waypoints which is merged into `.otrc`.

This permits, say, a family to pre-configure "Home", "Sports", etc. for certain or all members.

**Comment by ckrey** [comment]
or, we could split the waypoints from the config and add an `.otrw` and inline equivalent

**Comment by jpmens** [comment]
Also a good idea, but I think it'll be easier for users to create a JSON array of waypoints -- syntax is a bit easier.

**Comment by jpmens** [comment]
Also inline otrw would mean changing our android app which I'd like to avoid

**Comment by ckrey** [comment]
> Also a good idea, but I think it'll be easier for users to create a JSON array of waypoints -- syntax is a bit easier.

The waypoints array in .otrc is the same as in an  .otrw

**Comment by jpmens** [comment]
which is wrapped into a dict with two additional elements:

```json
{
  "waypoints" : [
    {
      "tst" : 1432817332,
      "lat" : 52.0,
      "_type" : "waypoint",
      "lon" : 6.0,
      "rad" : 0,
      "desc" : "Main@WestWing:DEADBEEF-ABBA-CAFE-AFFE-123456789012:0001"
    }
  ],
  "_type" : "waypoints"
}
```

We might support both:
- simple array of waypoints
- actual otrw files from which the list of waypoints is read

**Comment by jpmens** [comment]
Ready for testing. Documentation [here](https://owntracks.org/booklet/features/qs-config/#friend-specific-waypoints-regions).
