### ISSUE TITLE
Assertion failing during OwnTracks installation

### ISSUE THREAD

**Issue by bhnoronha** [owntracks/quicksetup#30]
Hi, I'm trying to install the latest version. However, I'm facing the following issues during the bootstrap phase:

TASK [verify some requirements] ************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "ansible_distribution_release in [ 'bookworm', 'jammy' ]",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

I'm running Ubuntu 23.10 and carefully followed all installation steps you provided.

tks!

**Comment by jpmens** [comment]
>I'm running Ubuntu 23.10 and carefully followed all installation steps you provided.

On line 38 of the file owntracks-setup.yml you'll see the line containing the two operating system names; comment the line out by inserting a hash character (#) at the beginning of the line, and try re-running ./bootstrap.sh please.

We've not yet tested with Ubuntu 23.10 which is the reason the assertion fails, but I hope the rest of the code will run through correctly. Let us know how it goes.

**Comment by jpmens** [comment]
Notes on instaling on Ubuntu 23.10:
- "Installing OwnTracks repository" takes an inordinate amount of time. But in apt-check? I hit CTL-C after about 1m and restart `./bootstrap.sh`

**Comment by jpmens** [comment]
@bhnoronha we've added support for Ubuntu 23.10, so please test and report back. To obtain the new files, perform these steps in your `quicksetup` directory:

```console
$ git checkout
$ git pull
$ sudo ./bootstrap.sh
```

**Comment by jpmens** [comment]
Closing as stale.
