### ISSUE TITLE
How-to change login password at https://owntracks.example/owntracks/ ?

### ISSUE THREAD

**Issue by GitHubQueenn** [owntracks/quicksetup#32]
Been following this: https://owntracks.org/booklet/guide/quicksetup/
I am using an Ubuntu VPS. It is all set up now and I was able to login to the page at https://owntracks.example/owntracks/

However, I wanted to change the password that was given to me automatically to something simple. So, in my VPS, I navigated to `/usr/local/owntracks/userdata/` and then did `nano username.pass`. I changed the password here, pressed `CTRL+X` to exit, then chose "Y" to save the file.

Well, when I go to login to https://owntracks.example/owntracks/, it is still taking the old password and not the new one I set, even after a reboot of the VPS, and even though the username.pass file is showing my new password that I wanted. Help?

**Comment by ckrey** [comment]
@GitHubQueenn the files in `/usr/local/owntracks/userdata` are only for your information, not the source of the passwords etc.

To set a password of your choice, edit `configuration.yaml` as shown below and re-run `./bootstrap.sh`.

(the optional password is not described in the setup guide, but only in the `configuration.yaml` file itself)

```
# configuration for OwnTracks backend quicksetup

# Specify your DNS domain, the name by which this OwnTracks

...

# Configure yourself and a list of friends who will be using
# this backend. Each friend will use their "username" to login
# to the site and to the apps. Their device is a "devicename"
# (this can be any suitable name, but we recommend you keep it
# generic so as to not have to change this if you move to a
# distinct device; i.e. "myphone" instead of "siemens-e2"),
# and their "tid" is a tracker- id which is used to label users
# on the map. A tid is a string of length two characters.
# Optionally a "password" may be set below; if omitted, passwords
# are generated and stored at /usr/local/owntracks/userdata/*.pass
# on this system.
#

friends:
  - { tid: UD, username: user, devicename: device, password:  yourpassword }
 
 ...
```

**Comment by jpmens** [comment]
Friend-specific passwords are [actually documented](https://owntracks.org/booklet/features/qs-config/#friend-specific-settings) in the Booklet, and linked to from the bottom of the [Quicksetup page](https://owntracks.org/booklet/guide/quicksetup/).

**Comment by GitHubQueenn** [comment]
@ckrey @jpmens Thank you. Real quick: how come one user here shows as "owntracks/b/phone" but the other as just "fs"? I would like to have "owntracks/b/phone" show as just the TID if possible, like the "fs" user does. Is that possible? Because when the one user sees the other, they show up on the map as "owntracks/b/phone" instead of their TID like "fs" does.

Looks like: https://i.imgur.com/WXZg6tm.png

Nowhere in my config or anywhere I see is the tid/names set to "owntracks/b/phone"

**Comment by jpmens** [comment]
TIDs are two characters and are configured on the device respectively via the autoconfiguration you might have done. I'm assuming one of the devices is publishing via HTTP which we reccomend you don't do: in /usr/local/owntracks/userdata you'll find `*.otrc` files which you send to the device (e.g. via email) and open it in OwnTracks there. The TID you configured in `configuration.yaml`.

**Comment by GitHubQueenn** [comment]
> TIDs are two characters and are configured on the device respectively via the autoconfiguration you might have done. I'm assuming one of the devices is publishing via HTTP which we reccomend you don't do: in /usr/local/owntracks/userdata you'll find `*.otrc` files which you send to the device (e.g. via email) and open it in OwnTracks there. The TID you configured in `configuration.yaml`.

Both devices are using MQTT. So far, for my friend and myself, we have just used my domain to log into the OwnTracks server and then tapped on the links to import the configs to our phones (Android & iPhone). The **only** place I see "owntracks/b/phone" is at this line:
`"subTopic": "owntracks/+/+ owntracks/+/+/event owntracks/+/+/info owntracks/b/phone/cmd",`
 The TID shows how I originally set it as "bb".

**Comment by jpmens** [comment]
You are saying there's a discrepancy between the TID in pubtopic and subtopic; that can only be due to editing of the configuration; I don't think there's a bug in the generation of our OTRC files.

Please don't confuse TID with the username contained in the topic.

**Comment by ckrey** [comment]
It is much easier to understand the issue here if you embed your images rather than using an external link:
<img width="273" alt="Bildschirmfoto 2024-03-22 um 09 02 59" src="https://github.com/owntracks/quicksetup/assets/4027289/033019de-3faf-49f1-940a-6b9b5667e388">

**Comment by ckrey** [comment]
Let me explain how it works and what you can do to change it:

<img width="649" alt="Bildschirmfoto 2024-03-22 um 09 08 31" src="https://github.com/owntracks/quicksetup/assets/4027289/7192b5f8-c860-4bc6-aa97-d0680b44fa6b">

The `Name` column uses the `topic` or if available the `name` field of the card published to the MQTT broker https://owntracks.org/booklet/features/card/#card.

The `TID` column shows the `tid` element of the location message. If the location message does not contain a `tid`, it uses the last two letters of the `topic`.

** In your case, `fs` has published a card (either via MQTT to the backend or directly from the iOS OwnTracks app) and `owntracks/b/phone` **

- In the `Frontend`, the `Name` is displayed.
- On the `Live map` the `TID` is displayed if available instead of the `topic` if no `name` is given

**Comment by GitHubQueenn** [comment]
The card made from fs was directly from the iPhone app. So how would we get rid of the "owntracks/b/phone" to just show "bb" like the other just shows "fs"?

**Comment by jpmens** [comment]
That question has been answered: publish a card for that user. Details are in the Booklet.

**Comment by jpmens** [comment]
Closing as answered.
