### ISSUE TITLE
[Bug?] Battery shows 0% no matter what at https://owntracks.domain.com/owntracks/table/

### ISSUE THREAD

**Issue by GitHubQueenn** [owntracks/quicksetup#34]
So, when I locally hosted OwnTracks in a Docker container on Windows, my battery percentage showed properly on the server localhost table URL. I am now using a Linux VPS and I noticed at the table URL (https://owntracks.domain.com/owntracks/table/), the battery is showing 0%, even though I am at 100%. Why is this?

Image showing 0%: https://i.imgur.com/21K430O.png

Not sure how it's work fine on Docker container but not now that I'm using a proper VPS. If it matters, was using HTTP mode on Docker, but MQTT on VPS.

**Comment by jpmens** [comment]
IIRC you are on an Androdi phone. Make sure "extra data" is switched ON in settings.

**Comment by jpmens** [comment]
Did that work, @GitHubQueenn ?

**Comment by jpmens** [comment]
Closing as answered.
