### ISSUE TITLE
Quicksetup: Where does the data live?

### ISSUE THREAD

**Issue by mssever** [owntracks/quicksetup#43]
I installed Owntracks using quicksetup. Both for the purposes of debugging an issue I'm facing and for planning a backup strategy, I'm wondering where the data lives. I haven't seen anything relevant in the documentation, nor have I found it by poking around my system.

**Comment by jpmens** [comment]
(issue transferred to Quicksetup issue tracker)

Data submitted via MQTT (or HTTP) to OwnTracks lives in the `<STORAGE>` directory of the [OwnTracks Recorder](https://github.com/owntracks/recorder). This is configured to be

```
/var/spool/owntracks/recorder/
```

below which there are a number of subdirectories.

[This page](https://github.com/owntracks/recorder/blob/master/doc/STORE.md) details a bit more on how the data is organized.

**Comment by mssever** [comment]
Thanks for the answer and for updating the documentation!
