### ISSUE TITLE
mosquitto restart issue during install

### ISSUE THREAD

**Issue by Roysteroonie** [owntracks/quicksetup#45]
I'm using IONOS VPS and have tried this a couple of times now. It fails at the same stage. Even reimagining my server and starting fresh it appears. Anyone else encountered this? 

![image](https://github.com/owntracks/recorder/assets/24797196/659518d6-9dc6-4ca0-9b4b-8f0672a2d968)

Using Ubuntu 22.4

Some further info. 

root@ubuntu:~# journalctl -xeu mosquitto.service
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit mosquitto.service has entered the 'failed' state with result 'exit-code'.
May 25 00:53:01 ubuntu systemd[1]: Failed to start Mosquitto MQTT Broker.
░░ Subject: A start job for unit mosquitto.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit mosquitto.service has finished with a failure.
░░
░░ The job identifier is 3958 and the job result is failed.
May 25 00:53:01 ubuntu systemd[1]: mosquitto.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ Automatic restarting of the unit mosquitto.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
May 25 00:53:01 ubuntu systemd[1]: Stopped Mosquitto MQTT Broker.
░░ Subject: A stop job for unit mosquitto.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A stop job for unit mosquitto.service has finished.
░░
░░ The job identifier is 4043 and the job result is done.
May 25 00:53:01 ubuntu systemd[1]: mosquitto.service: Start request repeated too quickly.
May 25 00:53:01 ubuntu systemd[1]: mosquitto.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit mosquitto.service has entered the 'failed' state with result 'exit-code'.
May 25 00:53:01 ubuntu systemd[1]: Failed to start Mosquitto MQTT Broker.
░░ Subject: A start job for unit mosquitto.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit mosquitto.service has finished with a failure.
░░
░░ The job identifier is 4043 and the job result is failed.

Any help or advice greatly appreciated.

**Comment by Roysteroonie** [comment]
Yeah I tried that, maybe the host had an issue. Anyway I removed my SSL which is ok as my main domain redirects to a shopify site anyway which already has SSL. So now after removing the SSL I reimaged and tried again, all worked!  Many thanks for your help.

**Comment by jpmens** [comment]
Glad you got it sorted.
