### ISSUE TITLE
Installing behind nginx proxy

### ISSUE THREAD

**Issue by dapelzaa** [owntracks/quicksetup#49]
Hello. 

I tried to install owntracks behind an existing nginx reverse proxy. 
TASK lego: enroll at letsencrypt failed. 
What can i do to fix this error? 

greets

**Comment by jpmens** [comment]
Quicksetup expects to be the sole inhabitant of a machine, so I'm afraid we have no clever solution for that.

Alternatively you could try to set up the individual bits and pieces (Recorder, Frontend, etc.), but that's a non-trivial task.

**Comment by jpmens** [comment]
Rereading your question: if you do not specify an email address in `configuration.yaml` then we don't perform LE enrollment. That might be your solution.

**Comment by dapelzaa** [comment]
Installation successful! 
On which port is owntracks?

**Comment by jpmens** [comment]
>On which port is owntracks?

if you mean the HTTP portion, that'd be 80 (or 443 in the case of configured Let's Encrypt).

**Comment by dapelzaa** [comment]
Okay. Server is running. 
But i cant connect from app to server. MessageProcessorEndpointMqtt: Failed to reconnect to MQTT broker

**Comment by jpmens** [comment]
The installed Mosquitto broker is listening on port 8883 with Let's Encrypt, and 1883 without.

I did say:

>Quicksetup expects to be the sole inhabitant of a machine

;-)

**Comment by dapelzaa** [comment]
my nginx reverse Proxy is available on port 80 and 443. and forwards to owntracks vps. 
i saw in own tracks config: port 8883 is in use. that could not work

**Comment by jpmens** [comment]
MQTT doesn't pass via an HTTP reverse proxy; it's an incompatible protocol.
