### ISSUE TITLE
Don't install a firewall

### ISSUE THREAD

**Issue by emiham** [owntracks/quicksetup#50]
I just ran the script to set up Owntracks, and ended up losing SSH access to my server. Eventually I figured out this was due to `ufw` blocking the ports, and I was able to fix it. It was not mentioned in the installation guide anywhere that a firewall was going to be installed, so I was very confused about what had happened before I finally figured it out. 

I don't think it's Owntracks's job to install a firewall, but if it really has to this has to be mentioned in the installation guide.

**Comment by jpmens** [comment]
Sorry this caused you trouble. Can you explain what happened? Did you per chance abort the installation?

UFW is configured to permit the following ports:

```
       - "ssh"
       - "80"
       - "443"
       - "8883"
```

so unless the installer aborted (which you haven't mentioned) or your SSH was on a port other than 22, I don't see what might have happened.

Please do elaborate.

**Comment by jpmens** [comment]
I might add we've run this innumerable times over SSH without losing access to the server.

**Comment by emiham** [comment]
Thank you for the quick reply!

I do have SSH on another port, so that explains that part. I still don't think it makes sense for this script to block all other ports, as users could have any number of other programs installed that would be blocked.

**Comment by jpmens** [comment]
That's a fair point.
