### ISSUE TITLE
Nginx web issues

### ISSUE THREAD

**Issue by buxxket** [owntracks/quicksetup#53]
I have successfully installed OwnTracks using the quicksetup on a rpi3.
Everything works, except when i visit my dns domain it shows:

Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to [nginx.org](http://nginx.org/).
Commercial support is available at [nginx.com](http://nginx.com/).

Thank you for using nginx.

![image](https://github.com/user-attachments/assets/49770d38-ac34-49b7-9bf7-5c3ca9ef27b8)

**Comment by jpmens** [comment]
I think what you're looking for ist at the httpS:// URL. :-)

**Comment by buxxket** [comment]
> I think what you're looking for ist at the httpS:// URL. :-)

Omg that's exactly it how embarrassing thank you haha

**Comment by jpmens** [comment]
glad it works.
