### ISSUE TITLE
ownTracks frontend without OpenStreetMaps

### ISSUE THREAD

**Issue by dietmarhein** [owntracks/quicksetup#57]
I followed installation guide: https://owntracks.org/booklet/guide/quicksetup/ and successfully installed all necessary components on a raspberry pi 3 B rev. 1.2

_system info
Last bootstrap: 2024-08-16T11:21:02Z
Ansible version: 2.17.3
OS distro: Debian / 12
OS distribution: bookworm_

"Live map" and "device table" work perfectly, mobile device reports location correctly.

**BUT**, when using "Frontend" instead of OpenStreetMaps just a light blue map is shown -> screenshot
[owntracks/frontend](https://github.com/owntracks/frontend) (2.15.3)

Any idea?
![ownTracks_Frontend](https://github.com/user-attachments/assets/56eda475-cd8f-44cb-95d4-9ab0182be320)

**Comment by jpmens** [comment]
That sounds a bit as though Frontend hasn't yet "seen" data from the Recorder API...

On the top right of Frontend is a selector for users & devices: do you see any data populated there?

And if a bit further on the left you select an older time range?

**Comment by dietmarhein** [comment]
![ownTracks_Frontend_info](https://github.com/user-attachments/assets/805c488d-2e8d-4eaa-a146-ebb62e2bb741)
that's all I see. Maybe some issues with user permissions? Version is never displayed [owntracks/recorder](https://github.com/owntracks/recorder) **(Loading version...)** when clicking on "information"
![ownTracks_Frontend_info](https://github.com/user-attachments/assets/877928aa-f9bc-426c-91e0-3b0d88a035a7)

**Comment by jpmens** [comment]
Can you please verify that the Recorder is actually running?

```
$ ps ax | grep recorder
```

and can you see if you can query it from the command line of your Raspi?

```
$ curl http://localhost:8083/api/0/version
```

As to the configuration you created in `configuration.yaml`: did you originally add an email address for Let's Encrypt to be activated?

**Comment by dietmarhein** [comment]
> Can you please verify that the Recorder is actually running?
> 
> ```
> $ ps ax | grep recorder
> ```
> 
> and can you see if you can query it from the command line of your Raspi?
> 
> ```
> $ curl http://localhost:8083/api/0/version
> ```
> 
> As to the configuration you created in `configuration.yaml`: did you originally add an email address for Let's Encrypt to be activated?

- yes, recorder is running
- curl http://localhost:8083/api/0/version -> {"version":"0.9.8","git":"0.9.8-0-g488eabe3e3"}
- yes, I originally added an email-address; Let's encrypt SSL certificate is present.

**Comment by jpmens** [comment]
Please check whether the content of Frontend's configuration makes sense, particularly the `baseUrl` value:

```
$ cat /usr/share/nginx/html/owntracks/frontend/config/config.js
```

(no need to paste that here, for privacy; if you're unsure, please send us the file to `support@owntracks.org` and we'll look at it)

If the file does make sense, and the URL is accessible *from* your Raspi to your Raspi (`curl` will tell you that), then I'm going to do something unusual and ask you to please reboot the Raspi ...

**Comment by jpmens** [comment]
To clarify: the `baseUrl` must be accessible from your Web browser.

**Comment by dietmarhein** [comment]
> To clarify: the `baseUrl` must be accessible from your Web browser.

Thank you very much for your hints. Finally I fixed the issue. 🤗

Problem was: I had to open another port than 443 at my ISP router forwarded to raspi 443.

I had to add the opened WAN port to `baseUrl` to get OpenStreetMaps working on Frontends page.

Maybe a feature for quicksetup would be to choose the local port at setup.

**Comment by jpmens** [comment]
Glad you got it working!

So in essence, your ISP offered you, say, TCP port `1009` which you are redirecting into `443`, so you've configured your `baseUrl` to be `https://example.org:1009/owntracks` for an _nginx_ on the Quicksetup machine running on 443.

I'll make a mental note to consider your feature request. However, one of the ideas behind _quicksetup_ was to keep it as simple (and thus configuration-free) as possible...

Please keep in mind for your own installation, that whenever you re-run `./bootstrap.sh`, say to add a friend, or reconfigure something, that your Frontend's `config.js` will be overwritten.

**Comment by dietmarhein** [comment]
> Glad you got it working!
> 
> So in essence, your ISP offered you, say, TCP port `1009` which you are redirecting into `443`, so you've configured your `baseUrl` to be `https://example.org:1009/owntracks` for an _nginx_ on the Quicksetup machine running on 443.
> 
> I'll make a mental note to consider your feature request. However, one of the ideas behind _quicksetup_ was to keep it as simple (and thus configuration-free) as possible...
> 
> Please keep in mind for your own installation, that whenever you re-run `./bootstrap.sh`, say to add a friend, or reconfigure something, that your Frontend's `config.js` will be overwritten.

yes, absolutly correct and I keep in mind that each time I do a re-run of `./bootstrap.sh`, I will have to reconfigure `config.js` to fit my needs regarding ISP WAN/LAN forwarding. Thanks again for pointing me to the problem!

**Comment by jpmens** [comment]
Closing with enhancement phrased in https://github.com/owntracks/quicksetup/issues/58
