### ISSUE TITLE
Map doesn't load: 'Blocked loading mixed active content'

### ISSUE THREAD

**Issue by lgrn** [owntracks/quicksetup#60]
Hi,

I'm trying to set up owntracks behind a reverse proxy, when I open `owntracks/frontend/` the map doesn't load and I can see this error in the browser console:

```
Blocked loading mixed active content “http://foo/owntracks/api/0/list”
```

I suspect this might be because I willingly configured quicksetup to run without an e-mail, because I don't want automatic cert renewals (the reverse proxy handles that), this means that the application is now listening on port 80, which is fine, but I guess this might also lead to the application having http links in HTML since it's unaware that https is actually being used.

Normally this is solved by some kind of configuration toggle that can let the application know that it's behind a reverse proxy, and that https links should be used throughout the application. Is anything like that available?

**Comment by jpmens** [comment]
You might need to tweak `/usr/share/nginx/html/owntracks/frontend/config/config.js` for your particular configuration, but please note this file is (currently) overwritten whenever you re-run `./bootstrap.sh`.

**Comment by jpmens** [comment]
Closing as answered
