### ISSUE TITLE
Failed to install a cron job for Let's Encrypt certificate renewals

### ISSUE THREAD

**Issue by nhan000** [owntracks/quicksetup#61]
I followed the instructions in the Quicksetup to the steps of running `$ sudo ./bootstrap.sh`, and I got the error message below:

```
TASK [lego: template out certificate/key installer] ************************************************************************************************
ok: [localhost]

TASK [lego: template out enroller] *****************************************************************************************************************
ok: [localhost]

TASK [lego: enroll at letsencrypt] *****************************************************************************************************************
changed: [localhost]

TASK [lego: get certificate information] ***********************************************************************************************************
ok: [localhost]

TASK [lego: display enrolled certificate subject] **************************************************************************************************
ok: [localhost] => {
    "msg": "Certificate Subject: nhan1234.online"
}

TASK [lego: install cron job for letsencrypt renewals] *********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"crontab\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=16   changed=2    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0
```

What can I do now? I'm running this on a VPS from Ultahost. Thanks for your help!

**Comment by nhan000** [comment]
Sorry if I appeared too lazy. Almost everything in the quicksetup is new to me and this is my first attempt at Linux, and I didn't know if I did something wrong.

It turns out that the folder name is “mygpsphone” even though I set it as “myGPSphone”, so I'd suggest to add a warning here in the Quicksetup.

I'm running into a new issue where the Frontend doesn't work

This is how it looks when I opened it:
![image](https://github.com/user-attachments/assets/2dbaa4a8-93e7-48cf-9973-0aa9eadf4937)
This is how it looks when zoomed out:
![image](https://github.com/user-attachments/assets/af24aab0-a269-4f17-bfb1-03c705440e9b)

It doesn't show any device here
![image](https://github.com/user-attachments/assets/a7a4c398-7056-4877-b7ad-ccb1b5172803)

There seem to be a similar issue https://github.com/owntracks/quicksetup/issues/57 and I have followed the troubleshoot up to this step https://github.com/owntracks/quicksetup/issues/57#issuecomment-2297343484, and I'm stuck here

> and the URL is accessible from your Raspi to your Raspi (curl will tell you that), then I'm going to do something unusual and ask you to please reboot the Raspi

because I'm running it using a VPS from Ultahost. I've rebooted my VPS but it didn't fix it.

Thanks a lot for your help!

**Comment by jpmens** [comment]
> I'd suggest to add a warning here in the Quicksetup to not use capital letters.

There's no need for a warning; capital letters are permitted, but we convert filenames to lowercase. Because you wanted to access the file directly (which most don't need to do) you stumbled over this which, btw, is documented in the documentation for the Recorder.

In the file `/usr/share/nginx/html/owntracks/frontend/config/config.js` is a URL. The value of `baseUrl` must be accessible to the Web browser you are using. I'm not familiar with with "Ultahost" so it might be they've got a proxy or something before your port 443. (In case of doubt ask their support).

From the command line, and using the value of your `baseURL` you should be able to run

```
curl -u username:password http://<baseURL>/api/0/version 
```

with _username_ and _password_ being what you configured in `configuration.yaml` respectively the user's password from `/usr/local/owntracks/userdata/<username>.pass`

**Comment by jpmens** [comment]
Good.

Now, the baseURL you used for that `curl` command (without the `/api/0/version` portion) should be the same you use in your Web browser. 

Maybe enable Web console (or Browser console) to see whether you recognize errors on the page indicating why Frontend cannot find the API data from the Recorder.

**Comment by nhan000** [comment]
Hey it's working now! Your previous mention of the port 443 made me think that it could be because of the port of my modem. I messed with the port forward when I was trying to set up Owntracks with VirtualBox. I did a reset of my modem and the Frontend shows up fine now.

Thank you so much for your help! Really appreciate it!

**Comment by jpmens** [comment]
I'm glad you got it working.

I'll close this now, but do open a new issue if you come across something untoward.
