### ISSUE TITLE
No devices available for friend's configuration 

### ISSUE THREAD

**Issue by github-login-1649** [owntracks/quicksetup#63]
I followed the quicksetup and got OwnTracks working on my Android by visiting the front end page on my Android and loading my .otrc file.  I ran bootstrap.sh with two entries in the friends array of configuration.yaml (me and one friend).  My friend's .otrc and .pass files are present in /usr/local/owntracks/userdata, and I can log in to the front end webpage using the credentials provided in those files.  However, when I log into the webpage using my friend's credentials, there are no devices available for configuration:

![image](https://github.com/user-attachments/assets/34b25003-29fc-4a19-98cc-ad9347cb39fd)

The behavior I expected was for the device listed in configuration.yaml to appear in the table above, with a link to the .otrc file for setup on the client device.

My friend was able to get OwnTracks working on their device by me emailing their .otrc file to them and importing manually in the app.

**Comment by jpmens** [comment]
Sorry to hear the experience isn't as smooth as we intended it to be...

Is it possible that your friend's username contains capital letters in it? If so, would you please change to lowercase in `configuration.yaml` and rerun `./bootstrap.sh` to then have your friend login with their lower-case username?

That's the one thing which occurs to me here.

**Comment by jpmens** [comment]
Maybe test with a different friend (which you can subsequently remove if you don't need it) to avoid your "real" friend having to reconfigure their device ...

**Comment by github-login-1649** [comment]
@jpmens Yes, my friend's username is all capital letters.  I must have missed that limitation.  Thanks for the quick reply.

**Comment by jpmens** [comment]
We've added clarification to the Booklet and to `configuration.yaml.example`.
