### ISSUE TITLE
Setting up the app on my phone

### ISSUE THREAD

**Issue by Bow3ryList** [owntracks/quicksetup#65]
So I have managed to setup Owntrack on my Raspberry Pi and log in to the user page. It mentioned in the quick guide that there should be a link at the bottom of the page to allow me to download a "At the bottom of the page is a link you can click on from your Android/iOS device to automatically configure the app" but I can't see any link. Have I done something wrong?

Attached is a photo.

![Screenshot_20241109_003307_Edge](https://github.com/user-attachments/assets/4f20f82b-3657-4c4d-bce5-98a34c0e0bfc)

Apologies if I have missed something obvious.

I'm not sure how to get the "/usr/local/owntracks/userdata/*.otrc" from the raspberry pi to my phone

Thanks in advance for your help

**Comment by jpmens** [comment]
have you actually configured users (lowercase username) in `configuration.yaml`? It doesn't look as though that has happened ... In case of doubt, please double check and rerun `./bootstrap.sh`

**Comment by Bow3ryList** [comment]
Okay, I tried again making the username just lowercase and it appears to be working now, although it is showing more devices that I had in the friends list

Are quotation marks needed within the friends list or does it make no difference?

 friends:
    - { tid: "jj", username: "username1",   devicename: "phone1" }
    - { tid: "ip", username: "username2",    devicename: "phone2"}

Thanks in advance for your help

**Comment by jpmens** [comment]
Glad you're getting it sorted.

In YAML (`configuration.yaml` is in YAML format) strings need not be quoted, but it's good practice to do so.

If you are seeing more devices on your smartphone, then I assume you're using MQTT with a broker to which other devices have already published data; is that possible?

If it is your broker, respectively if you have authorization to do so you can clear out those old publishes by publishing a retained null value to the appropriate topic.

**Comment by jpmens** [comment]
Closing as answered.
