### ISSUE TITLE
iPhone iOS 18 | App not waking up

### ISSUE THREAD

**Issue by sybadm** [owntracks/quicksetup#70]
Hi,

All my Region configuration has Home|1|2 , Office|1|2 etc... I also have defined region +follow with radius:50
I use App with exact same region configuration for me, wife and son iPhone.

If App is open or is in foreground (Move mode=2) then MQTT messages works flawlessly, when I enter into any defined region app moves into background (significant mode=1) which works as expected. But after leaving region app is not waking up after moving 500 m/5 mins rule and as backup +follow region should kick-off and wake up application?

Another problem if the person is in the defined region (example my wife is at home in Significant=1) and other people (me and my son) are on Move=2. although our phones are publishing the live location but my wife phone is in background and does not receives any notification.

I'm not sure how all this app foreground/background and wake-up are handled by Life360

**Comment by ckrey** [comment]
Are you sure you have enables Settings/Privacy/Location services = always for the OwnTracks app? Otherwise background wakeup will not happen.

Life360 is using different mechanisms to wake-up phones. They rely on a central component and Silent Push Messages we both don't use for privacy reasons.

**Comment by sybadm** [comment]
@ckrey thanks for you response. 

Yes Location service is set to always for Owntracks app on all of our iPhones

**Comment by sybadm** [comment]
@ckrey You were right wife phone was not set to Always. Which explains why we were not receiving her updated location.

Any thoughts on my 2nd Q
Another problem if the person is in the defined region (example my wife is at home in Significant=1) and other people (me and my son) are on Move=2. although our phones are publishing the live location but my wife phone is in background and does not receives any notification.

Thanks

**Comment by ckrey** [comment]
She will receive the notification the next time her phone connects to the backend either by moving or manual opening . There is no Push Service waking up her phone.

**Comment by ckrey** [comment]
Have look at this tool: https://github.com/mqtt-tools/mqttwarn
It already have the necessary components

**Comment by sybadm** [comment]
thank you
