### ISSUE TITLE
Ansible related error(s)

### ISSUE THREAD

**Issue by Sud0nym4315** [owntracks/quicksetup#71]
I'm attempting to set up owntracks on a raspberry pi. After reaching the last step and running ./bootstrap.sh, I see the following error:

```
ERROR! couldn't resolve module/action 'community.crypto.x509_certificate_info'. This often indicates a misspelling, missing collection, or incorrect module path.`

The error appears to be in '/root/quicksetup/owntracks-setup.yml': line 171, column 16, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


             - name: "lego: get certificate information"
               ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

```

I wasn't sure if this was due to missing software on the machine or a genuine syntax error, so I didn't touch the owntracks-setup.yml. 

Any advice/insight?

**Comment by jpmens** [comment]
I wonder .. did you install Ansible yourself?

Please try again, by resetting the installation (this will not destroy your `configuration.yaml`):

```console
$ sudo rm -rf /usr/local/owntracks/ansible
$ sudo ./bootstrap.sh
```

I'm particularly interested in the initial output of the script, please, as from where it tells you `Attempting to install ansible and prerequisites for bootstrapping`

It's as though this step either didn't run or incorrectly. (`$ADIR` is defined in `bootstrap.sh`)

```
        sudo -u ansible $ADIR/bin/ansible-galaxy collection install \
                community.general \
                community.crypto
```

**Comment by Sud0nym4315** [comment]
> I wonder .. did you install Ansible yourself?
> 
> Please try again, by resetting the installation (this will not destroy your `configuration.yaml`):
> 
> ```
> $ sudo rm -rf /usr/local/owntracks/ansible
> $ sudo ./bootstrap.sh
> ```
> 
> I'm particularly interested in the initial output of the script, please, as from where it tells you `Attempting to install ansible and prerequisites for bootstrapping`
> 
> It's as though this step either didn't run or incorrectly. (`$ADIR` is defined in `bootstrap.sh`)
> 
> ```
>         sudo -u ansible $ADIR/bin/ansible-galaxy collection install \
>                 community.general \
>                 community.crypto
> ```

No, i didn't install it myself. However you might be on to something. 

I wasn't sure if it was relevant at all, but my *first* run of bootstrap.sh yielded a simple locale error. I saw pip working, but then ansible said it couldn't find a supported locale.  It was a bit strange to me, but I ran `dpkg-reconfigure locales`. That's when the next error popped up. So in short, the initial install was interrupted briefly.

I'll reset the installation and see if that fixes it.

**Comment by Sud0nym4315** [comment]
This is the new output after removing `/usr/local/owntracks/ansible`:
```
root@rpi:~/quicksetup# ./bootstrap.sh 
Attempting to install ansible and prerequisites for bootstrapping
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease   
Get:4 http://download.zerotier.com/debian/bookworm bookworm InRelease [36.9 kB]
Hit:5 http://archive.raspberrypi.com/debian bookworm InRelease                           
Hit:6 https://archive.heckel.io/apt debian InRelease      
Fetched 36.9 kB in 1s (27.8 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
117 packages can be upgraded. Run 'apt list --upgradable' to see them.
python3-pip is already the newest version (23.0.1+dfsg-1+rpt1).
python3-venv is already the newest version (3.11.2-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 117 not upgraded.
useradd: user 'ansible' already exists
Error: [Errno 13] Permission denied: '/usr/local/owntracks/ansible'
sudo: /usr/local/owntracks/ansible/bin/pip: command not found
sudo: /usr/local/owntracks/ansible/bin/ansible-galaxy: command not found
./bootstrap.sh: line 50: /usr/local/owntracks/ansible/bin/ansible-playbook: No such file or directory
```

**Comment by jpmens** [comment]
Please investigate why this directory is there, and why 'permission denied'

```
Error: [Errno 13] Permission denied: '/usr/local/owntracks/ansible'
```

In case of doubt, remove that directory and its content.

**Comment by jpmens** [comment]
and you might remove the `ansible` user with `sudo userdel -f -r ansible`

**Comment by Sud0nym4315** [comment]
Thank you for the help. The issue was solved. Funny enough, the ansible dir didn't actually exist so i'm not sure what the `permission denied` error was all about. But deleting the ansible user and home directory is what did it. I re-ran ./bootstrap.sh and it's working like a charm.

**Comment by jpmens** [comment]
Glad to hear.

(If the `ansible` user didn't exist, then its home directory didn't exist, so our bootstrap couldn't create directories there-in as user `ansible`.)

**Comment by mvdstelt** [comment]
I have the exact same error, trying to install OwnTracks on a Raspberry Pi 3B, running Raspberry Pi OS 13 (trixie) (32 bit):


ERROR! Error when getting collection version metadata for community.crypto:3.1.0 from default (https://galaxy.ansible.com/api/) (HTTP Code: 500, Message: Internal Server Error Code: Unknown)
ERROR! couldn't resolve module/action 'community.crypto.x509_certificate_info'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/tracker-tracker/quicksetup/owntracks-setup.yml': line 186, column 16, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


             - name: "lego: get certificate information"
               ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"



Also, in my situation the ansible dir doesn't exist. Then when I delete the 'usr/local/owntracks/' directory (ansible was not there) with sudo rm -rf /usr/local/owntracks/ and run bootstrap again. If I run sudo rm -rf /usr/local/owntracks/ansible it is of course not actioned as ansible is not there.


Running bootstrap, I get:
This program will overwrite existing files! Hit ENTER to continue: 
Attempting to install ansible and prerequisites for bootstrapping
Hit:1 http://archive.raspberrypi.com/debian trixie InRelease                           
Hit:2 http://raspbian.raspberrypi.com/raspbian trixie InRelease                        
109 packages can be upgraded. Run 'apt list --upgradable' to see them.
python3-pip is already the newest version (25.1.1+dfsg-1+rpt1).
python3-venv is already the newest version (3.13.5-1).
gpg is already the newest version (2.4.7-21+deb13u1).
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 109
useradd: user 'ansible' already exists
Error: [Errno 13] Permission denied: '/usr/local/owntracks'
sudo: /usr/local/owntracks/ansible/bin/pip: command not found
sudo: /usr/local/owntracks/ansible/bin/ansible-galaxy: command not found
./bootstrap.sh: line 53: /usr/local/owntracks/ansible/bin/ansible-playbook: No such file or directory


After this, when running bootstrap again, the initial error appears up again. Also, the usr/local/owntracks/ created again still without ansible.
Also I am not sure where the ansible user sits in the system to run 'sudo userdel -f -r ansible'

Thanks for your time.

**Comment by jpmens** [comment]
```
ERROR! Error when getting collection version metadata for community.crypto:3.1.0 from default (https://galaxy.ansible.com/api/) (HTTP Code: 500, Message: Internal Server Error Code: Unknown)
```

Would seem like Ansible Galaxy failed; nothing we can do.
Re-run `./bootstrap.sh` at a later time.

**Comment by jpmens** [comment]
Note that [Ansible Galaxy has been broken for over 24 hours](https://forum.ansible.com/t/galaxy-ansible-com-currently-down-500-errors/45170/21), so this'll be a while....

**Comment by mvdstelt** [comment]
> ```
> ERROR! Error when getting collection version metadata for community.crypto:3.1.0 from default (https://galaxy.ansible.com/api/) (HTTP Code: 500, Message: Internal Server Error Code: Unknown)
> ```
> 
> Would seem like Ansible Galaxy failed; nothing we can do. Re-run `./bootstrap.sh` at a later time.

Thanks for the quick reply. I will be patient then.
